language: python
python: 2.7
sudo: false

addons:
  apt:
    packages:
    - python-wxgtk2.8 
    - python-dev 
    - build-essential 
    - mysql-server 
    - mysql-client 
    - graphviz 
    - docbook 
    - dblatex 
    - python-pip 
    - python-numpy 
    - git 
    - libmysqlclient-dev
    - texlive-latex-extra 
    - docbook-utils

services: 
 - mysql

install: "pip install mysql-python==1.2.3 pyparsing==1.5.7 pydot"

before_script:
 - mysql --user=root --password='' < CAIRIS/cairis/cairis/test/createdb.sql
 - mysql --user=irisuser --password='' --database=arm < CAIRIS/cairis/cairis/sql/init.sql
 - mysql --user=irisuser --password='' --database=arm < CAIRIS/cairis/cairis/sql/procs.sql

script: echo foo
