language: python
python: 2.7
sudo: false

addons:
  apt:
    packages:
    - python-dev 
    - build-essential 
    - mysql-server 
    - mysql-client 
    - graphviz 
    - python-pip 
    - python-numpy 
    - git 
    - libmysqlclient-dev

env:
- PYTHONPATH=. CAIRIS_SRC=$PYTHONPATH/cairis CAIRIS_CFG=$CAIRIS_SRC/config/cairis.cnf 

install: "pip install mysql-python==1.2.3 pyparsing==1.5.7 pydot pytest python-coveralls"

before_script:
 - pip install -r test_requirements.txt --use-mirrors 
 - mysql --user=root --password='' < $CAIRIS_SRC/test/createdb.sql
 - mysql --user=irisuser --password='' --database=arm < $CAIRIS_SRC/sql/init.sql
 - mysql --user=irisuser --password='' --database=arm < $CAIRIS_SRC/sql/procs.sql

script: 
 - py.test --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  coveralls
