language: python
python: 
 - "2.6"
 - "2.7"

sudo: false

addons:
  apt:
    packages:
    - python-dev 
    - build-essential 
    - mysql-server 
    - mysql-client 
    - graphviz 
    - python-pip 
    - python-numpy 
    - git 
    - libmysqlclient-dev

env:
- PYTHONPATH=. CAIRIS_SRC=$PYTHONPATH/cairis CAIRIS_CFG=$CAIRIS_SRC/config/cairis.cnf 
- TOX_ENV=py27-1.6.X
- TOX_ENV=py27-1.5.X
- TOX_ENV=py27-1.4.X
- TOX_ENV=py26-1.5.X
- TOX_ENV=py26-1.4.X

install:
   pip install tox
 - pip install -r requirements
 - pip install -r test_requirements.txt
 - pip install coveralls

script: 
  - py.test cairis/test --doctest-modules -v --cov cairis/core --cov-report term-missing
  - tox -e $TOX_ENV

after_success:
  coveralls
