language: python
python: 
 - "2.6"
 - "2.7"

sudo: false

addons:
  apt:
    packages:
    - python-wxglade 
    - python-glade2 
    - python-wxgtk3.0
    - python-dev 
    - build-essential 
    - mysql-server 
    - mysql-client 
    - graphviz 
    - python-pip 
    - python-numpy 
    - git 
    - libmysqlclient-dev
    - texlive-latex-extra 
    - docbook-utils

env:
- PYTHONPATH=. CAIRIS_SRC=$PYTHONPATH/cairis CAIRIS_CFG=$CAIRIS_SRC/config/cairis.cnf 
- TOX_ENV=py27-1.6.X
- TOX_ENV=py27-1.5.X
- TOX_ENV=py27-1.4.X
- TOX_ENV=py26-1.5.X
- TOX_ENV=py26-1.4.X

install:
- pip install tox
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install coveralls

script: 
- py.test cairis/test --doctest-modules -v --cov cairis/core --cov-report term-missing
- tox -e $TOX_ENV

after_success:
  coveralls
