language: python
python: 2.7
sudo: false

addons:
  apt:
    packages:
    - python-wxgtk2.8 
    - python-dev 
    - build-essential 
    - mysql-server 
    - mysql-client 
    - graphviz 
    - docbook 
    - dblatex 
    - python-pip 
    - python-numpy 
    - git 
    - libmysqlclient-dev
    - texlive-latex-extra 
    - docbook-utils

services: 
 - mysql

install: "pip install mysql-python==1.2.3 pyparsing==1.5.7 pydot"

before_script:
 - mysql -e 'GRANT USAGE ON *.* TO 'irisuser'@'localhost' IDENTIFIED BY '' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;'
 - mysql -e 'CREATE DATABASE IF NOT EXISTS `arm`;'
 - mysql -e 'GRANT ALL PRIVILEGES ON `irisuser`.* TO `arm`@`localhost`;'
 - mysql --user=irisuser --password='' --database=arm < CAIRIS/cairis/cairis/sql/init.sql
 - mysql --user=irisuser --password='' --database=arm < CAIRIS/cairis/cairis/sql/procs.sql

script: echo foo
