# Site settings
title: CAIRIS
markdown: redcarpet

description: > # this means to ignore newlines until "baseurl:"
  Computer Aided Integration of Requirements and Information Security
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cairis.org" # the base hostname & protocol for your site
twitter_username: ShamalFaily
github_username:  failys
# Build settings
